### ISSUE TITLE
Error running on Fedora 36

### ISSUE THREAD

**Issue by Melluish** [optyfr/JRomManager#169]
Downloaded and installed the RPM. Running it from the applications menu does nothing. Running it from the terminal produces the attached log.
[jrommanager.log](https://github.com/optyfr/JRomManager/files/8864820/jrommanager.log)

**Comment by optyfr** [comment]
the bundled jdk has troubles with your fedora 36, specifically there is a libharfbuz conflict with the system one, I know this bug to happen on manjaro and arch, but it is not supposed to happen on fedora/rh (according oracle issue)... anyway it has been fixed since jdk 11.0.12 (bundled version was jdk 11.0.10)
there is 2 possibilities for you
- use the noarch rpm (and it will use the jdk from your system)
- wait for JRomManager 3.0 which will use jdk 17 and javafx (and no more swing)

**Comment by Melluish** [comment]
I tried installing the noarch version but got the following:

```
error: Failed dependencies:
	java = 1:11 is needed by jrommanager-0:2.5.1-1.noarch
```

**Comment by optyfr** [comment]
It means that you must find and install the rpm of java jdk 11
A beginning of solution here :
https://www.linuxcapable.com/how-to-install-openjdk-11-on-fedora-36-linux/#Install_OpenJDK_11_LTS

**Comment by Melluish** [comment]
Thanks for the help but even after installing Java with:

```
sudo dnf install java-11-openjdk -y
```

I still get the same error when trying to install JRomManager:

```
error: Failed dependencies:
	java = 1:11 is needed by jrommanager-0:2.5.1-1.noarch
```

**Comment by optyfr** [comment]
OK The feature provided by the java RPM package is now "java-11" and not anymore "java" with a separate version

**Comment by optyfr** [comment]
it will be fixed in 3.0.0
